### ISSUE TITLE
Question: What is the reason for the dependency on Node >=8.11.x <=9 ?

### ISSUE THREAD

**Issue by MossP** [AmitM30/react-native-typescript-boilerplate#23]
No bug, just a question :)

ps. I'm looking forward to trying this out.

**Comment by AmitM30** [comment]
Hi @MossP. No specific reason. Just that I haven't run the code in the LTS and versions above these.

Also have been using the version 8.11.x for some time now. Being a public repo, I cannot assumably say that things will work in 8 and above :), without testing it myself.

Please feel free to PR the `package.json` if it works for you fine.

**Comment by MossP** [comment]
Thanks @AmitM30. I'll give it a try and report back once I'm sure all is OK 👍
