### ISSUE TITLE
Build script for iOS

### ISSUE THREAD

**Issue by tomtom125** [AmitM30/react-native-typescript-boilerplate#31]
It would be great if an npm script would be there for ios ipa build. (without the need of a mac and xcode).

**Comment by AmitM30** [comment]
hi @tomtom125, as far as I know, I do not think there is any way of doing it (at least straight forward). One does require a mac and xcode to do the build iOS app.

**Comment by AmitM30** [comment]
Closing this. Please re-open if you feel there is a way.
